# -*- coding: utf-8 -*-
"""TSUGradRates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vt1adI5Wfya3ASL_8MotEv9oPHWkvTC3
"""

pip install streamlit

import streamlit as st
import pandas as pd
import numpy as np

# --- Sample Chatbot Knowledge Base ---
chatbot_data = [
    {"module": "Academic Advising", "question": "How do I register for classes?", "response": "You can register via the Banner system under Student Services > Registration."},
    {"module": "Academic Advising", "question": "What are the prerequisites for Calculus II?", "response": "Calculus I with a grade of C or better is required."},
    {"module": "Academic Advising", "question": "How can I drop a class?", "response": "You can drop a class through the Banner system before the drop deadline."},
    {"module": "Financial Aid", "question": "How do I apply for financial aid?", "response": "Fill out the FAFSA form at studentaid.gov and use TSU's school code."},
    {"module": "Financial Aid", "question": "When will I receive my financial aid?", "response": "Aid is disbursed within the first two weeks of the semester."},
    {"module": "Financial Aid", "question": "What scholarships are available?", "response": "Visit the TSU Scholarships Office website for a full list of current scholarships."},
    {"module": "Course Registration", "question": "What classes are required for my major?", "response": "Check your Degree Works audit or contact your academic advisor."},
    {"module": "Course Registration", "question": "Can I register for a class without the prerequisite?", "response": "You need special permission from the department to override prerequisites."},
    {"module": "Course Registration", "question": "Why can't I register for a class?", "response": "Check for holds on your account or if the class is full."}
]
chatbot_df = pd.DataFrame(chatbot_data)

# --- Simulated Risk Dashboard Data ---
np.random.seed(42)
n_students = 50
risk_df = pd.DataFrame({
    'Student ID': [f"S{i:03d}" for i in range(n_students)],
    'GPA': np.round(np.random.uniform(1.5, 4.0, n_students), 2),
    'Attendance %': np.random.randint(40, 100, n_students),
    'Engagement': np.random.randint(1, 10, n_students),
})
risk_df['Risk Score'] = ((2.3 - risk_df['GPA']) / 2.3 + (70 - risk_df['Attendance %']) / 70) / 2
risk_df['Risk Score'] = risk_df['Risk Score'].clip(0, 1)
risk_df['Risk Level'] = pd.cut(risk_df['Risk Score'], bins=[0, 0.4, 0.7, 1], labels=['Low', 'Medium', 'High'])

# --- Streamlit App ---
st.set_page_config(page_title="TSU AI Platform", layout="centered")
st.title("🎓 TSU AI-Powered Student Success App")

tab1, tab2 = st.tabs(["🤖 Chatbot Assistant", "📊 Risk Dashboard"])

# --- Chatbot Tab ---
with tab1:
    st.subheader("AI Chatbot Assistant")
    st.markdown("Ask questions about **academic advising**, **financial aid**, or **course registration**.")
    user_input = st.text_input("Ask a question:")

    def get_response(user_input):
        user_input = user_input.lower()
        for _, row in chatbot_df.iterrows():
            if any(word in user_input for word in row["question"].lower().split()):
                return f"**[{row['module']}]** {row['response']}"
        return "I'm sorry, I couldn't find an answer to your question. Please contact your advisor."

    if user_input:
        st.markdown(get_response(user_input))

# --- Risk Dashboard Tab ---
with tab2:
    st.subheader("📈 Student Risk Dashboard")
    selected_risk = st.selectbox("Filter by Risk Level", ["All", "Low", "Medium", "High"])
    if selected_risk != "All":
        filtered_df = risk_df[risk_df['Risk Level'] == selected_risk]
    else:
        filtered_df = risk_df
    st.dataframe(filtered_df, use_container_width=True)