# -*- coding: utf-8 -*-
"""TSUGradRates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vt1adI5Wfya3ASL_8MotEv9oPHWkvTC3
"""

import streamlit as st
import pandas as pd
import numpy as np

# --- TSU Branding ---
st.set_page_config(page_title="TSU AI Student Success", layout="centered")
st.image("https://www.tnstate.edu/images/TSU_Logo.png", width=200)
st.title("🎓 TSU AI-Powered Student Success Platform")

# --- Expanded Chatbot Knowledge Base ---
chatbot_data = [
    {"module": "Academic Advising", "question": "How do I register for classes?", "response": "Register through TSU Banner Self-Service under Student Services."},
    {"module": "Academic Advising", "question": "How can I drop a class?", "response": "You can drop courses via Banner or consult your advisor before the drop deadline."},
    {"module": "Financial Aid", "question": "How do I apply for financial aid?", "response": "Submit your FAFSA at studentaid.gov and use TSU’s school code 003522."},
    {"module": "Tutoring", "question": "Where can I get help with math or writing?", "response": "TSU Learning Support Centers offer tutoring—visit the library or online tutoring portal."},
    {"module": "Mental Health", "question": "Who do I talk to about mental health?", "response": "Contact TSU Counseling Center at (615) 963-5611 or visit Floyd-Payne Campus Center Room 304."},
    {"module": "IT Help", "question": "I forgot my TSU email password.", "response": "Visit helpdesk.tnstate.edu or call IT Help Desk at (615) 963-7777."}
]
chatbot_df = pd.DataFrame(chatbot_data)

# --- Simulated Risk Dashboard Data ---
np.random.seed(42)
n_students = 50
risk_df = pd.DataFrame({
    'Student ID': [f"S{i:03d}" for i in range(n_students)],
    'GPA': np.round(np.random.uniform(1.5, 4.0, n_students), 2),
    'Attendance %': np.random.randint(40, 100, n_students),
    'Engagement': np.random.randint(1, 10, n_students),
})
risk_df['Risk Score'] = ((2.3 - risk_df['GPA']) / 2.3 + (70 - risk_df['Attendance %']) / 70) / 2
risk_df['Risk Score'] = risk_df['Risk Score'].clip(0, 1)
risk_df['Risk Level'] = pd.cut(risk_df['Risk Score'], bins=[0, 0.4, 0.7, 1], labels=['Low', 'Medium', 'High'])

tab1, tab2 = st.tabs(["🤖 Chatbot Assistant", "📊 Risk Dashboard"])

# --- Chatbot Tab ---
with tab1:
    st.subheader("AI Chatbot Assistant")
    st.markdown("Ask about TSU advising, financial aid, IT, tutoring, or wellness services.")
    user_input = st.text_input("Ask a question:")

    def get_response(user_input):
        user_input = user_input.lower()
        for _, row in chatbot_df.iterrows():
            if any(word in user_input for word in row["question"].lower().split()):
                return f"**[{row['module']}]** {row['response']}"
        return "I’m sorry, I couldn’t find the answer. Please contact your TSU advisor or support office."

    if user_input:
        st.markdown(get_response(user_input))

# --- Risk Dashboard Tab ---
with tab2:
    st.subheader("📈 Student Risk Dashboard")
    selected_risk = st.selectbox("Filter by Risk Level", ["All", "Low", "Medium", "High"])
    if selected_risk != "All":
        filtered_df = risk_df[risk_df['Risk Level'] == selected_risk]
    else:
        filtered_df = risk_df
    st.dataframe(filtered_df, use_container_width=True)
    st.download_button("Download CSV", data=filtered_df.to_csv(index=False), file_name="tsu_risk_data.csv")

st.markdown("---")
st.caption("🔵 Powered by TSU Office of Academic Affairs • [tnstate.edu](https://www.tnstate.edu)")